---

- name: Include Raspberry-Pi MOTD.
  ansible.builtin.import_playbook: playbooks/raspberry-pi-motd.yml

- name: Include Control-Plane MOTD.
  ansible.builtin.import_playbook: playbooks/control-plane-motd.yml

- name: Bootstrap Kubernetes prerequisites
  hosts: control_plane:workers
  roles:
    - k8s_common

- name: Bootstrap Kubernetes control plane
  hosts: control_plane
  roles:
    - k8s_control_plane

- name: Bootstrap Kubernetes workers
  hosts: workers
  roles:
    - k8s_worker

- name: Initial machine setup
  hosts: workers

  tasks:
    - name: Setup Git
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.apt:
        name: git
    - name: Setup xRDP
      block:
        - name: Install xRDP
          become: true
          become_method: ansible.builtin.sudo
          ansible.builtin.apt:
            name: xrdp
        - name: Add xRSP to SSL-Cert Group
          become: true
          become_method: ansible.builtin.sudo
          ansible.builtin.user:
            name: '{{ ansible_user_id }}'
            append: true
            groups:
              - ssl-cert
        - name: Allow users to use Colord
          become: true
          become_method: ansible.builtin.sudo
          vars:
            source_path: 45-allow-colord.pkla
          ansible.builtin.copy:
            src: "{{ source_path }}"
            dest: /etc/polkit-1/localauthority/50-local.d/
            mode: "0644"

- name: Include Oh-My-ZSH.
  ansible.builtin.import_playbook: playbooks/oh-my-zsh.yml

- name: Include Machine Learning.
  ansible.builtin.import_playbook: playbooks/machine-learning.yml
