---

- name: Include Raspberry-Pi MOTD.
  ansible.builtin.import_playbook: playbooks/raspberry-pi-motd.yml

- name: Initial machine setup
  hosts: all

  tasks:
    - name: Setup Git
      ansible.builtin.apt:
        name: git
    - name: Setup xRDP
      block:
        - name: Install xRDP
          become: true
          become_method: ansible.builtin.sudo
          ansible.builtin.apt:
            name: xrdp
        - name: Add xRSP to SSL-Cert Group
          become: true
          become_method: ansible.builtin.sudo
          ansible.builtin.user:
            name: '{{ ansible_user_id }}'
            append: true
            groups:
              - ssl-cert
        - name: Allow users to use Colord
          become: true
          become_method: ansible.builtin.sudo
          vars:
            source_path: 45-allow-colord.pkla
          ansible.builtin.copy:
            src: "{{ source_path }}"
            dest: /etc/polkit-1/localauthority/50-local.d/
            mode: "0644"
    - name: Ensure Snapd installed.
      become: true
      ansible.builtin.apt:
        name: snapd

- name: Include Oh-My-ZSH.
  ansible.builtin.import_playbook: playbooks/oh-my-zsh.yml

- name: Include MicroK8s.
  ansible.builtin.import_playbook: playbooks/microk8s.yml
