---
- name: Include Raspberry-Pi MOTD.
  ansible.builtin.import_playbook: tasks/raspberry-pi-motd.yaml

- name: Initial machine setup
  hosts: all

  tasks:
  - name: Setup Git 
    apt: 
      name: git
      state: latest
  - name: Setup Zsh
    block: 
      - name: install zsh
        become: true
        become_method: sudo
        ansible.builtin.apt: 
          name: zsh
          state: latest
      - name: Check for Oh-My-Zsh
        ansible.builtin.stat:
          path: ~/.oh-my-zsh
        register: omz
      - name: Install Oh-My-Zsh
        ansible.builtin.shell:
          cmd: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
        when: not omz.stat.exists
      - name: Change Theme
        ansible.builtin.replace:
          path: ~/.zshrc
          regexp: ZSH_THEME="robbyrussell"
          replace: ZSH_THEME="alanpeabody"
      - name: Change shell
        become: true
        become_method: sudo
        ansible.builtin.user:
          name: '{{ ansible_user_id }}'
          shell: /bin/zsh  
  - name: Setup xRDP
    block: 
      - name: install xRDP
        become: true
        become_method: sudo
        ansible.builtin.apt: 
          name: xrdp
          state: latest
      - name: add xrdp to ssl-cert group
        become: true
        become_method: sudo
        ansible.builtin.user:
          name: '{{ ansible_user_id }}'
          append: true
          groups: 
            - ssl-cert
      - name: Allow users to use Colord
        become: true
        become_method: sudo
        ansible.builtin.copy:
          src: ../files/45-allow-colord.pkla
          dest: /etc/polkit-1/localauthority/50-local.d/
  - name: Ensure Snapd installed.
    become: true
    ansible.builtin.apt:
      name: snapd
      state: latest
  - name: Setup MicroK8s
    block:
      - name: Install MicroK8s
        become: true
        become_method: sudo
        community.general.snap:
          name: microk8s
          classic: true
          state: present
      - name: add user
        become: true
        become_method: sudo
        ansible.builtin.user:
          name: '{{ ansible_user_id }}'
          append: true
          groups: 
            - microk8s