---
all:
  children:
    control_plane:
      hosts:
        k8s-cp: # Ubuntu Server 24.04 control-plane VM
          ansible_host: control-plane.k8s.internal
    workers:
      hosts:
        pi5-gpio:
          ansible_host: gpio.k8s.internal
        pi5-ml:
          ansible_host: ml.k8s.internal
    ml:
      hosts:
        pi5-ml: {}
