---
- name: Raspberry-Pi MOTD
  hosts: pis

  tasks:
  - name: Copy MOTD
    become: true
    become_method: sudo
    ansible.builtin.copy:
      src: ../files/raspberry-pi-motd
      dest: /etc/update-motd.d/51-raspberry-pi-motd
      mode: +x
  - name: check MOTD
    ansible.builtin.slurp:
      src: /etc/motd
    register: motd_value
  - name: Erase Default MOTD
    become: true
    become_method: sudo
    ansible.builtin.copy:
      content: ""
      dest: /etc/motd
    when: motd_value != ""