#!/usr/bin/env sh

# If not running interactively, don't do anything
#[ -z "$PS1" ] && return

# set a fancy prompt (non-color, unless we know we "want" color)
# case "$TERM" in
#     xterm-color) color_prompt=yes;;
# esac


upSeconds="$(/usr/bin/cut -d. -f1 /proc/uptime)"
secs=$((upSeconds%60))
mins=$((upSeconds/60%60))
hours=$((upSeconds/3600%24))
days=$((upSeconds/86400))
free_memory=$(cat /proc/meminfo | grep MemAvailable | awk {'print $2'})
total_memory=$(cat /proc/meminfo | grep MemTotal | awk {'print $2'})
PERCENT_MEM=$(bc -l << EOF
    (($total_memory-$free_memory)/$total_memory)* 100 
EOF
)
UPTIME=$(printf "%d days, %02dh%02dm%02ds" "$days" "$hours" "$mins" "$secs")


if /sbin/ifconfig end0 | /bin/grep -n "inet "; then
    local_ip=$(/sbin/ifconfig end0 | /bin/grep "inet ")
el if /sbin/ifconfig eth0 | /bin/grep -n "inet "
    local_ip=$(/sbin/ifconfig eth0 | /bin/grep "inet ")
else 
    local_ip=$(/sbin/ifconfig wlan0 | /bin/grep "inet ")
fi

# get the load averages
read one five fifteen rest < /proc/loadavg

printf "\e[0;32m
   .~~.   .~~.    $(date +"%A, %e %B %Y, %r")
  '. \ ' ' / .'   $(uname -srmo)\e[m\e[0;31m
   .~ .~~~..~.    
  : .~.'~'.~. :   Uptime.............: ${UPTIME}
 ~ (   ) (   ) ~  Memory.............: $(printf "%.2f" "$PERCENT_MEM")%% of $((total_memory/1000/1000))GB (Total)
( : '~'.~.'~' : ) Load Averages......: ${one}, ${five}, ${fifteen} (1, 5, 15 min)
 ~ .~ (   ) ~. ~  Running Processes..: $(ps ax | wc -l | tr -d " ")
  (  : '~' :  )   IP Addresses.......: $(echo "$local_ip" | /usr/bin/awk -F ' ' '{print $2}') and $(wget -q -O - http://icanhazip.com/ | tail)
   '~ .~~~. ~'    Temp...............: $(vcgencmd measure_temp | awk -F '=' '{print $2}')
       '~'        Weather............: $(curl -s "http://rss.accuweather.com/rss/liveweather_rss.asp?metric=0&locCode=11210" | sed -n '/Currently:/ s/.*: \(.*\): \([0-9]*\)\([CF]\).*/\2°\3, \1/p')
\e[m"
