---

- name: Install Docker
  hosts: pis

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    # - name: Save package facts to file
    #   ansible.builtin.copy:
    #     dest: /tmp/package_facts.json
    #     content: "{{ ansible_facts.packages | to_nice_json }}"
    #     mode: "0644"

    - name: Install Docker when not present
      when: "'docker.io' not in ansible_facts.packages"
      block:
        - name: Remove conflicting Docker packages
          become: true
          ansible.builtin.apt:
            name:
              - docker.io
              - docker-compose
              - docker-doc
              - podman-docker
              - containerd
              - runc
            state: absent
            purge: true

        - name: Update apt cache
          become: true
          ansible.builtin.apt:
            update_cache: true
            cache_valid_time: 3600

        - name: Install Docker dependencies
          become: true
          ansible.builtin.apt:
            name:
              - apt-transport-https
              - ca-certificates
              - curl
              - gnupg
              - lsb-release
            state: present

        - name: Create keyrings directory
          become: true
          ansible.builtin.file:
            path: /etc/apt/keyrings
            state: directory
            mode: "0755"

        - name: Add Docker GPG key
          become: true
          ansible.builtin.get_url:
            url: https://download.docker.com/linux/debian/gpg
            dest: /etc/apt/keyrings/docker.asc
            mode: "0644"

        - name: Add Docker repository
          become: true
          ansible.builtin.apt_repository:
            repo: "deb [arch=arm64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
            state: present
            filename: docker

        - name: Install Docker
          become: true
          ansible.builtin.apt:
            name: docker-ce
            state: present

        - name: Install Docker Compose
          become: true
          ansible.builtin.apt:
            name: docker-compose-plugin
            state: present

        - name: Start Docker service
          become: true
          ansible.builtin.systemd:
            name: docker
            state: started
            enabled: true

        - name: Add user to docker group
          become: true
          ansible.builtin.user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: true

        - name: Reset SSH connection to apply new group membership
          ansible.builtin.meta: reset_connection
