---

- name: Install Docker
  hosts: pis

  tasks:
    - name: Remove conflicting Docker packages
      become: true
      ansible.builtin.apt:
        name:
          - docker.io
          - docker-compose
          - docker-doc
          - podman-docker
          - containerd
          - runc
        state: absent
        purge: true

    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Docker dependencies
      become: true
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG key
      become: true
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/raspbian/gpg
        state: present

    - name: Add Docker repository
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [arch=armhf] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      become: true
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Install Docker Compose
      become: true
      ansible.builtin.apt:
        name: docker-compose
        state: present

    - name: Start Docker service
      become: true
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Reset SSH connection to apply new group membership
      ansible.builtin.meta: reset_connection
