- name: Raspberry-Pi MOTD
  hosts: workers

  tasks:
    - name: Copy MOTD
      become: true
      become_method: ansible.builtin.sudo
      vars:
        source_path: raspberry-pi-motd
      ansible.builtin.copy:
        src: "{{ source_path }}"
        dest: /etc/update-motd.d/51-raspberry-pi-motd
        mode: +x
    - name: Check MOTD
      ansible.builtin.slurp:
        src: /etc/motd
      register: motd_value
    - name: Erase Default MOTD
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.copy:
        content: ""
        dest: /etc/motd
        mode: "0644"
      when: (motd_value.content | b64decode) != ""
    - name: Check env file groups
      ansible.builtin.shell: grep -c 'PATH' /etc/environment || true
      changed_when: false
      register: env_file
    - name: Append Groups
      become: true
      become_method: ansible.builtin.sudo
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games"
      when: env_file.stdout == "0"
